-- MySQL Script generated by MySQL Workbench
-- Sun Oct 19 21:17:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema superfotopamplona
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema superfotopamplona
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `superfotopamplona` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `superfotopamplona` ;

-- -----------------------------------------------------
-- Table `superfotopamplona`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superfotopamplona`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `superfotopamplona`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superfotopamplona`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(150) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `superfotopamplona`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superfotopamplona`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `cargo` VARCHAR(50) NULL DEFAULT NULL,
  `direccion` VARCHAR(150) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  `foto` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `superfotopamplona`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superfotopamplona`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `superfotopamplona`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superfotopamplona`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(50) NOT NULL,
  `contraseña` VARCHAR(100) NOT NULL,
  `id_rol` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `id_rol` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `superfotopamplona`.`rol` (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `superfotopamplona`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superfotopamplona`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NULL DEFAULT NULL,
  `id_empleado` INT NULL DEFAULT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  `fecha_pedido` DATE NOT NULL,
  `hora_entrega` TIME NULL DEFAULT NULL,
  `estado` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `id_empleado` (`id_empleado` ASC) VISIBLE,
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `pedido_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `superfotopamplona`.`cliente` (`id_cliente`),
  CONSTRAINT `pedido_ibfk_2`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `superfotopamplona`.`empleado` (`id_empleado`),
  CONSTRAINT `pedido_ibfk_3`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `superfotopamplona`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `superfotopamplona`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superfotopamplona`.`proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `documento_nit` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(150) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  `web` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `superfotopamplona`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superfotopamplona`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `id_categoria` INT NULL DEFAULT NULL,
  `id_proveedor` INT NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
  INDEX `id_proveedor` (`id_proveedor` ASC) VISIBLE,
  CONSTRAINT `producto_ibfk_1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `superfotopamplona`.`categoria` (`id_categoria`),
  CONSTRAINT `producto_ibfk_2`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `superfotopamplona`.`proveedor` (`id_proveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `superfotopamplona`.`detallepedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superfotopamplona`.`detallepedido` (
  `id_detalle_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_pedido` INT NULL DEFAULT NULL,
  `id_producto` INT NULL DEFAULT NULL,
  `precio_unidad` DECIMAL(10,2) NULL DEFAULT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `descuento` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_detalle_pedido`),
  INDEX `id_pedido` (`id_pedido` ASC) VISIBLE,
  INDEX `id_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `detallepedido_ibfk_1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `superfotopamplona`.`pedido` (`id_pedido`),
  CONSTRAINT `detallepedido_ibfk_2`
    FOREIGN KEY (`id_producto`)
    REFERENCES `superfotopamplona`.`producto` (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
